// Mocks generated by Mockito 5.1.0 from annotations
// in flutter_application_1/test/user_use_case_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:firebase_auth/firebase_auth.dart' as _i3;

import 'package:flutter_smart_wallet/repository/remote/user/user_remote_repository.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeFirebaseAuth_6 extends _i1.Fake implements _i3.FirebaseAuth {}

/// A class which mocks [UserRemoteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRemoteRepository extends _i1.Mock
    implements _i6.UserRemoteRepository {
  MockUserRemoteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.FirebaseAuth get firebaseAuth =>
      (super.noSuchMethod(Invocation.getter(#firebaseAuth),
          returnValue: _FakeFirebaseAuth_6()) as _i3.FirebaseAuth);
  @override
  String getUserId() => (super.noSuchMethod(
        Invocation.method(#getUserId, []),
        returnValue: '',
      ) as String);
  @override
  String getPhoneNumber() => (super.noSuchMethod(
        Invocation.method(#getPhoneNumber, []),
        returnValue: '',
      ) as String);

  @override
  _i5.Future<bool> setUserFirestore(Map<String, Object?>? data) =>
      (super.noSuchMethod(Invocation.method(#setUserFirestore, [data]),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
  @override
  _i5.Future<bool> hasUserFirestore() =>
      (super.noSuchMethod(Invocation.method(#hasUserFirestore, []),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
  @override
  _i5.Future<bool> updateUserFirestore(Map<String, Object?>? data) =>
      (super.noSuchMethod(Invocation.method(#updateUserFirestore, [data]),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
  @override
  _i5.Future<bool> hasconnection() =>
      (super.noSuchMethod(Invocation.method(#hasconnection, []),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
}
