// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9niQ96SFJeY4UC0CbvntwWFqZQ5g9vq4',
    appId: '1:1090821933223:web:9e286a283b430367007382',
    messagingSenderId: '1090821933223',
    projectId: 'smart-wallet-d598c',
    authDomain: 'smart-wallet-d598c.firebaseapp.com',
    storageBucket: 'smart-wallet-d598c.appspot.com',
    measurementId: 'G-4M1XF3V2KJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_s4DNjZuncznK6E3SumozC6iw_AhEDDU',
    appId: '1:1090821933223:android:d7224e1b69b812e6007382',
    messagingSenderId: '1090821933223',
    projectId: 'smart-wallet-d598c',
    storageBucket: 'smart-wallet-d598c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChDbJU_y5Vf90WHD_06ck_gVr9IgMt9M8',
    appId: '1:1090821933223:ios:2d9dd4c9d7ae4371007382',
    messagingSenderId: '1090821933223',
    projectId: 'smart-wallet-d598c',
    storageBucket: 'smart-wallet-d598c.appspot.com',
    androidClientId: '1090821933223-7u1ut75gh7ordda9o6i8dulc6sfff3pj.apps.googleusercontent.com',
    iosBundleId: 'vn.com.kma.hatuan314.espend',
  );
}
