// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDBlsQ2zt7a9VexMM_espYPhFEdX7J7Qg',
    appId: '1:771634101510:web:5e20270d2affe5c3b7f287',
    messagingSenderId: '771634101510',
    projectId: 'e-spend',
    authDomain: 'e-spend.firebaseapp.com',
    storageBucket: 'e-spend.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNoYSHe4R-F09KFiKkcFbG4Q-TgKL1jBA',
    appId: '1:771634101510:android:54f21da15155784bb7f287',
    messagingSenderId: '771634101510',
    projectId: 'e-spend',
    storageBucket: 'e-spend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH9OhKdcCeHE5nVKYLgXEVQVwUDJ6Po8A',
    appId: '1:771634101510:ios:e45969c0da5d9825b7f287',
    messagingSenderId: '771634101510',
    projectId: 'e-spend',
    storageBucket: 'e-spend.appspot.com',
    iosBundleId: 'vn.com.kma.hatuan314.espend',
  );
}
